#!/system/bin/sh

if [ -z ${SD_EXT_DIRECTORY} ]
then
    SD_EXT_DIRECTORY=/sd-ext
fi

grep -q ${SD_EXT_DIRECTORY} /proc/mounts
if [ ! $? -eq 0 ]
then
    log -p e -t apps2sd "${SD_EXT_DIRECTORY} not mounted. Not enabling Apps2SD."
    exit 0
fi

if [ ! -d ${SD_EXT_DIRECTORY}/dalvik-cache ]
then
    install -m 771 -o 1000 -g 1000 -d ${SD_EXT_DIRECTORY}/dalvik-cache
    log -p i -t apps2sdext "Created ${SD_EXT_DIRECTORY}/dalvik-cache"
fi

if [ -d /data/app_i ]
then
    for dir in app app-private
    do
        if [ ! -d ${SD_EXT_DIRECTORY}/${dir} ]
        then
            install -m 771 -o 1000 -g 1000 -d ${SD_EXT_DIRECTORY}/${dir}
            log -p i -t apps2sdext "Created ${SD_EXT_DIRECTORY}/${dir}"
        fi
        mv /data/${dir}_i/* /data/${dir}/ 2> /dev/null
        rmdir ${dir}_i 2>/dev/null
    done
    find ${SD_EXT_DIRECTORY}/app ${SD_EXT_DIRECTORY}/app-private \
        -type l -exec rm {} \;
    if [ -e "/data/system/packages.xml" ]
    then
        for apk in `ls /sd-ext/app/*apk /sd-ext/app-private/*apk`
        do
            # update packages.xml with apk's location
            sed s~/data/`basename $apk`~/sd-ext/`basename $apk`~ -i /data/system/packages.xml
            # clear dalvik-cache ( will probably get generated on /sd-ext )
            rm /data/dalvik-cache/*`basename $apk`*.dex 2> /dev/null
        done
    fi
fi

setprop cm.a2sd.active 1
